CREATE TABLE users(user_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, user_name VARCHAR(60) NOT NULL, oauth_token VARCHAR(100), oauth_token_secret VARCHAR (100));

ALTER TABLE users(ADD COLUMN active INT NOT NULL, ADD COLUMN hashtag VARCHAR (200), ADD COLUMN tweet_time DATETIME, ADD COLUMN counter INT NOT NULL);
